// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkjznlobbilwfpavgbar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ranpubG9iYmlsd2ZwYXZnYmFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDk1NzksImV4cCI6MjA2MDkyNTU3OX0.mfoYK-LZNxJHBrphRsJ83jr-8nb5reK64-u59_BSJeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);